include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    # temporary rules
    strict-casts: false
    strict-raw-types: false
    strict-inference: false

linter:
  rules:
    # temporary rules
    flutter_style_todos: false
    one_member_abstracts: false
    lines_longer_than_80_chars: false
    prefer_int_literals: false
    avoid_unused_constructor_parameters: false
    use_setters_to_change_properties: false
    prefer_asserts_with_message: false
    public_member_api_docs: false
    avoid_dynamic_calls: false
    avoid_positional_boolean_parameters: false
    comment_references: false
    cascade_invocations: false
