include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    # temporary rules
    strict-casts: false

linter:
  rules:
    # temporary rules
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    avoid_dynamic_calls: false
    avoid_positional_boolean_parameters: false
    comment_references: false
    cascade_invocations: false
